apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: miniflux
  name: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - image: miniflux/miniflux:latest
          name: miniflux
          envFrom:
          - configMapRef:
              name: miniflux-config
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
