apiVersion: v1
kind: Service
metadata:
  labels:
    app: miniflux
  name: miniflux
spec:
  ports:
  - name: "20080"
    port: 20080
    targetPort: 8080
  selector:
    app: miniflux
status:
  loadBalancer: {}
