kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: planka-data
  labels:
    app: planka
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Mi