apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planka
  name: planka
spec:
  selector:
    matchLabels:
      app: planka
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: planka
    spec:
      containers:
        - image: meltyshev/planka:latest
          imagePullPolicy: Always
          name: planka
          envFrom:
          - configMapRef:
              name: planka-config
          ports:
            - containerPort: 1337
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
          - name: planka-data
            mountPath: /app/public/user-avatars
          - name: planka-data
            mountPath: /app/public/project-background-images
          - name: planka-data
            mountPath: /app/public/attachments
      restartPolicy: Always
      volumes:
      - name: planka-data
        persistentVolumeClaim:
          claimName: planka-data
status: {}
