---
- name: Prepare Ubuntu environment
  hosts: localhost
  vars:
    username: michalkozak
  connection: local
  become: yes
  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
  tasks:
    - name: Install Docker dependancies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker's stable repo
      apt_repository:
        update_cache: yes
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker Engine
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: Download Docker-Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Create Docker group
      group:
        name: docker
        state: present
    - name: Add user to Docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
    - name: Add Plastic SCM's stable repo
      lineinfile:
        path: /etc/apt/sources.list.d/plasticscm-stable.list
        line: deb https://www.plasticscm.com/plasticrepo/stable/ubuntu/ ./
        create: yes
    - name:  Add Plastic SCM's apt-get key
      apt_key: 
        url: https://www.plasticscm.com/plasticrepo/stable/ubuntu/Release.key
        state: present
    - name: Install Plastic SCM client
      apt:
        update_cache: yes
        name: plasticscm-client-core
        state: present
    - name: Copy Plastic SCM client configuration file
      copy:
        src: /home/{{ username }}/plasticscmclient.conf
        dest: /home/{{ username }}/.plastic4/client.conf
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0664"
    - name: Set memory limit for Elasticsearch
      lineinfile:
        path: /etc/sysctl.conf
        line: vm.max_map_count=262144