apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.michalkozak.cz`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
    middlewares:
    - name: security

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.michalkozak.cz`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
    middlewares:
    - name: security
  tls:
    certResolver: myresolver
    options:
      name: kazumatlsoption
      namespace: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-tls
  namespace: default
spec:
  routes:
  - match: Host(`kazuma.michalkozak.cz`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares: 
    - name: basic-auth
    - name: security
  tls:
    certResolver: myresolver
    options:
      name: kazumatlsoption
      namespace: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: miniflux-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`miniflux.michalkozak.cz`)
    kind: Rule
    services:
    - name: miniflux
      port: 20080
    middlewares:
    - name: security
  tls:
    certResolver: myresolver
    options:
      name: kazumatlsoption
      namespace: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: archiv
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`archiv.michalkozak.cz`)
    kind: Rule
    services:
    - name: caddy
      port: 30081
    middlewares:
    - name: security

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: archiv-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`archiv.michalkozak.cz`)
    kind: Rule
    services:
    - name: caddy
      port: 30081
    middlewares:
    - name: security
  tls:
    certResolver: myresolver
    options:
      name: kazumatlsoption
      namespace: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`michalkozak.cz`)
    kind: Rule
    services:
    - name: caddy
      port: 30080
    middlewares:
    - name: security

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`michalkozak.cz`)
    kind: Rule
    services:
    - name: caddy
      port: 30080
    middlewares:
    - name: security
  tls:
    certResolver: myresolver
    options:
      name: kazumatlsoption
      namespace: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: graphite
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`graphite.michalkozak.cz`)
    kind: Rule
    services:
    - name: graphite-statsd
      port: 80
    middlewares:
    - name: security
    - name: basic-auth

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: graphite-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`graphite.michalkozak.cz`)
    kind: Rule
    services:
    - name: graphite-statsd
      port: 80
    middlewares:
    - name: security
    - name: basic-auth
  tls:
    certResolver: myresolver
    options:
      name: kazumatlsoption
      namespace: default

# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRouteUDP
# metadata:
#   name: statsd
# spec:
#   entryPoints:
#     - statsd
#   routes:
#   - services:
#     - name: graphite-statsd
#       port: 8125
#       weight: 10