apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: 7.6.12 # renovate: depName=argoproj/argo-helm extractVersion=^argo-cd-(?<version>.+)$
    chart: argo-cd
    helm:
      values: |
        applicationSet:
          enabled: "false"
        dex:
          enabled: "false"
        configs:
          params:
            server.insecure: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
