apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://charts.gabe565.com"
    targetRevision: 0.15.1 # renovate: depName=gabe565/charts extractVersion=^memos-(?<version>.+)$
    chart: memos
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: memos
