apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.gabe565.com'
    targetRevision: 0.2.0
    chart: miniflux
  destination:
    server: "https://kubernetes.default.svc"
    namespace: miniflux