apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: miniflux
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.gabe565.com'
    targetRevision: 0.1.7
    chart: miniflux
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: miniflux
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true