apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://charts.gabe565.com"
    targetRevision: 0.6.2 # renovate: depName=gabe565/charts extractVersion=^miniflux-(?<version>.+)$
    chart: miniflux
    helm:
      values: |
        env:
          CREATE_ADMIN: "0"
          POLLING_FREQUENCY: "5"
          POLLING_PARSING_ERROR_LIMIT: "0"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: miniflux
