apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 21.2.1
    chart: traefik
    helm:
      values: |
        persistence:
          enabled: true
          name: data
          accessMode: ReadWriteOnce
          size: 128Mi
          storageClass: microk8s-hostpath
          path: /data
        certResolvers:
          letsencrypt:
            email: me@michalkozak.cz
            tlsChallenge: true
            httpChallenge:
              entryPoint: "web"
            storage: /data/acme.json
        service:
          externalIPs:
            - 94.112.245.206
          spec:
            externalTrafficPolicy: Cluster
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: traefik