apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://traefik.github.io/charts"
    targetRevision: 25.0.0 # renovate: depName=traefik/traefik-helm-chart extractVersion=^v(?<version>.+)$
    chart: traefik
    helm:
      values: |
        persistence:
          enabled: true
          name: data
          accessMode: ReadWriteOnce
          size: 128Mi
          storageClass: microk8s-hostpath
          path: /data
        certResolvers:
          letsencrypt:
            email: me@michalkozak.cz
            tlsChallenge: true
            httpChallenge:
              entryPoint: "web"
            storage: /data/acme.json
        logs:
          access:
            enabled: true
        service:
          externalIPs:
            - 94.112.245.206
          spec:
            externalTrafficPolicy: Cluster
        providers:
          kubernetesIngress:
            ingressEndpoint:
              publishedService: "traefik/traefik"
            publishedService:
              enabled: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: traefik
