apiVersion: v1
kind: Service
metadata:
  labels:
    app: caddy
  name: caddy
spec:
  ports:
  - name: "30080"
    port: 30080
    targetPort: 80
  - name: "30081"
    port: 30081
    targetPort: 8080
  selector:
    app: caddy
status:
  loadBalancer: {}
