apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: caddy
  name: caddy-config
data:
  Caddyfile: |
      :80 {
          root * /usr/share/caddy/web
          file_server
      }

      :8080 {
          root * /usr/share/caddy/archiv
          file_server
      }