apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caddy
  name: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - image: caddy:latest
          name: caddy
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
          - name: caddy-data
            mountPath: /usr/share/caddy
          - name: caddy-config
            mountPath: /etc/caddy/Caddyfile
            subPath: Caddyfile
      restartPolicy: Always
      volumes:
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-data
      - name: caddy-config
        configMap:
          name: caddy-config
          items:
            - key: Caddyfile
              path: Caddyfile
              mode: 0644
status: {}
