apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: caddy
  name: caddy-data
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/michalkozak/caddy
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kazuma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi