apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphite-statsd
  name: graphite-statsd
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8125"
    protocol: UDP
    port: 8125
    targetPort: 8125
  selector:
    app: graphite-statsd
status:
  loadBalancer: {}
