apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: graphite-statsd
  name: graphite-statsd
spec:
  selector:
    matchLabels:
      app: graphite-statsd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graphite-statsd
    spec:
      containers:
        - image: graphiteapp/graphite-statsd:latest
          name: graphite-statsd
          ports:
          - containerPort: 80
          - containerPort: 8125
            protocol: UDP
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1"
      restartPolicy: Always
status: {}
