apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: praqma
  name: praqma
spec:
  selector:
    matchLabels:
      app: praqma
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: praqma
    spec:
      containers:
        - image: praqma/network-multitool:latest
          name: praqma
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1"
      restartPolicy: Always
status: {}
