apiVersion: ENC[AES256_GCM,data:vAA=,iv:z1peGyb5u4FZPbCx6Mq8QYOh5mwO3QbfM5V7mbIl3Pg=,tag:uSLK7UngKEu6QUkc4B+VRA==,type:str]
kind: ENC[AES256_GCM,data:A6OKCO9T3aeo,iv:oeYGHQg+tHgP0Vpu0jRuP9XWC2I+WyqZJwJ51fFekK8=,tag:zHpepy7LXeexQKP9wAkRHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kgKgJAL1EW0CCFQubztP,iv:ZL4prVV8rdI9bBdEWeFhXi2cVsIl2Td2mGPuQ5/AVh0=,tag:u6PqByiwl/3SXW5YRA32Aw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:FhEL8aCo5Ro=,iv:C9I+T+Mt95IXzhM4/2q8dNSayzJ/wUR5qfItV5fJKQE=,tag:Al1HqJLjSg3Tc3+UATN3Qg==,type:str]
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CL5fTgjJoatpODvzm4jRFr9VS1YlUK+Kjxlgk5ldbCSkvakqwBBbKw0bZ71uzCK7pcxyRhGlPLD5Y8Tw40MAtnhsWU1ptgyC,iv:X3F3xvIPDH8AI+J9cqct1sQ9Y21aOd7qkk43UgjJT6U=,tag:hUZT2xssz7bg+xRCqlX6fA==,type:str]
    PGDATA: ENC[AES256_GCM,data:2LeEKmeGuq9ZVyQzz1R+p93Di4V+lT28k3/SnR9SIw==,iv:8L/ibZ4s3VbZfLmSgZytVatw5hs3Ftl9dr3bJgXmVAc=,tag:Un7V0P1P2wSEqudUQmjapA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-08-17T22:00:29Z'
    mac: ENC[AES256_GCM,data:ItcBZcOjd+e2M3DnAZ4uIyK4rYk73JaNjo3V0F6kXNj3XMTXjUhNU0hLp/4bfNFDAPey4fegvTpzTe07n4xI0uLv8gR9AzRdIMRpghiuyaBDHVkqT8GosflLIRhxCYkQZliZGrzWusyezLgwyo0H+iRVxRJKuqD5UHz5Aj7UTN4=,iv:dmr8xVAWWtauWCsntv7NlzfAGiizn4RuDwI186v+bqE=,tag:xysEFx0Dt9zo4osE/SuqPg==,type:str]
    pgp:
    -   created_at: '2020-08-17T22:00:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1JaOm7dWwxIAQ/+IQtMCRpVbnnC4GiWBh4ENb4gHJtS198rirEEsDP9UgsV
            XEymY/Q182dBi78cJ5UtPyaUO0uM8EnhGa80eTFKvyuAD7ulevlCXfgmSYNUagQV
            Nvl5zQQTWAfdY/RYpwhlG5ts3+abzgSteEUzZiAzDUtPryc0ldjnjMnqj/NrEWJ7
            2LImFJGxLam1pLHvbLm7mippMzVuH5C2EXLwzFMDIXEKpWE6q2EdbTeWiiiLve3a
            ZufMYYo2h3Gy+ISqXF1cE7KDkxGQQpAR4GhqDoa/Bm8idSR2clA0b45R2HN6V8t6
            KPZlPqICT/ABMoPcnvSp9MxrkWxp4EgYc66/IXyjfOUgTDZmPPL7dtK3EJg5GxFN
            /k3QmJ6sl0h/akO5OAy2wvZtB6V8hYdf2X8ZYXwdGT5h3Jz+jvRAL1eeMyhStzKF
            GhvSEogZ5SXF+CDcH35erUHRJXabJNNqWSL9VRrWAZgKbg07iV/I9dXkDdpBwD/9
            80LUm5K43oPzwb1XOn2WFBGydDDRrNOCo1a6LfrBBMnBdFdD05VHUa3GGxBpF4dr
            y/GLGIR8JwCPAlKwrphDn9TzKzqgQpsBQdWyqtVgj0gCNLeeBXlhu5bDWFS012oQ
            ogUUki7I6gIM3MshMOJKx/1Z0FjGdKDPXwSqhNEB7GmdaKVUL1jXNz/YcVUOuvLS
            XAG4Pk611OZ54xysyi9FZsgry2gLF1JU4toHsA6UQ6RC5fpQaYUczTEK9I/7YuLH
            PyTbb3E9Pk58thbsGCw38DVPPwSAPpJ1nBMmjYc6WyAi+UA4kBjMbJC0YA4q
            =a1kH
            -----END PGP MESSAGE-----
        fp: 49B80217DD9E370CFA0337DAAF4D653CE6436B7A
    unencrypted_suffix: _unencrypted
    version: 3.6.0
