apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:latest-ubuntu
          name: grafana
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1"
          volumeMounts:
          - name: grafana-data
            mountPath: /var/lib/grafana
          - name: grafana-config
            mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini
      restartPolicy: Always
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
      - name: grafana-config
        configMap:
          name: grafana-config
          items:
            - key: grafana.ini
              path: grafana.ini
              mode: 0644
status: {}
