name: Build and deploy the website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ivy
      - name: Build website with Ivy
        run: |
          cd static-sites/ivy
          ivy build
      - name: Copy static files to webserver
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOSTNAME}}
          username: ${{secrets.SSH_USERNAME}}
          port: 22
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "static-sites/ivy/out/*"
          target: "/home/${{secrets.SSH_USERNAME}}/caddy/web"
