name: Test K8s connection

on:
  workflow_dispatch:
  push:
    branches:
      - "k8s-test"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          cat kubeconfig
