name: Build and deploy the website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ivy
      - name: Build website with Ivy
        run: |
          cd static-sites/ivy
          ivy build
      - name: Copy static files to webserver
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: static-sites/ivy/out/
          remote_path: /home/${{secrets.SSH_USERNAME}}/caddy/web
          remote_host: ${{secrets.SSH_HOSTNAME}}
          remote_user: ${{secrets.SSH_USERNAME}}
          remote_key: ${{secrets.SSH_PRIVATE_KEY}}
          remote_port: ${{secrets.SSH_PORT}}
