name: Test K8s connection

on:
  workflow_dispatch:
  push:
    branches:
      - "k8s-test"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export DEPLOYMENT_NAMESPACE="test"
          export KUBECONFIG="./kubeconfig"
          cat <<< "${{ secrets.KUBECONFIG }}" > kubeconfig
          if [ ! "$(kubectl get namespace ${DEPLOYMENT_NAMESPACE})" ]; then
            kubectl create namespace "${DEPLOYMENT_NAMESPACE}"
            kubectl wait --for=condition=available --timeout=60s namespace/${DEPLOYMENT_NAMESPACE}
          fi
          kubectl get namespace
