name: Test K8s connection

on:
  workflow_dispatch:
  push:
    branches:
      - "k8s-test"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export DEPLOYMENT_NAMESPACE="test"
          cat <<< "${{ secrets.KUBECONFIG }}" > kubeconfig
          if [ ! "$(kubectl --kubeconfig kubeconfig get namespace ${DEPLOYMENT_NAMESPACE})" ]; then
            kubectl create namespace "${DEPLOYMENT_NAMESPACE}"
          fi
          kubectl wait --for=condition=Ready --timeout=60s namespace/${DEPLOYMENT_NAMESPACE}
          kubectl --kubeconfig kubeconfig get namespace
