name: Test K8s connection

on:
  workflow_dispatch:
  push:
    branches:
      - "k8s-test"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Update deployment manifest
        uses: mikefarah/yq@v4.35.1
        with:
          cmd: |
            export DEPLOYMENT_NAMESPACE=$(yq eval '.jobs.docker.runs-on' ./.github/workflows/main.yml)
            echo $DEPLOYMENT_NAMESPACE
            export IMAGE_TAG="sha-$(echo ${{ github.sha }} | cut -c1-7 )"
            echo $IMAGE_TAG
      # - run: |
      #     echo $DEPLOYMENT_NAMESPACE
      #     export DEPLOYMENT_NAMESPACE=$(yq eval '.jobs.docker.runs-on' ./.github/workflows/main.yml)
      #     echo $DEPLOYMENT_NAMESPACE
      #     # export DEPLOYMENT_NAMESPACE="test"
      #     export KUBECONFIG="./kubeconfig"
      #     cat <<< "${{ secrets.KUBECONFIG }}" > kubeconfig
      #     if [ ! "$(kubectl get namespace ${DEPLOYMENT_NAMESPACE})" ]; then
      #       kubectl create namespace "${DEPLOYMENT_NAMESPACE}"
      #       kubectl wait --for=jsonpath='{.status.phase}'=Active --timeout=60s namespace/${DEPLOYMENT_NAMESPACE}
      #     fi
      #     kubectl get namespace
